<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>netstandard2.1</TargetFramework>
        <Nullable>enable</Nullable>

        <!-- NuGet Metadata -->
        <PackageId>Berdsk.Sdk.PagarMe.V5</PackageId>
        <AssemblyName>Berdsk.Sdk.PagarMe.V5</AssemblyName>
        <RootNamespace>Berdsk.Sdk.PagarMe.V5</RootNamespace>
        <Title>Berdsk.Sdk.PagarMe.V5</Title>
        <Authors>Berdsk</Authors>
        <Company>Berdsk</Company>
        <Description>Biblioteca não oficial para integração com a API PagarMe v5. SDK moderno e tipado para facilitar transações de cartão, boleto, pix e gestão de assinaturas. Integração completa.</Description>
        <PackageTags>pagarme;pagamento;gateway;sdk;v5;pix;boleto;assinaturas;berdsk</PackageTags>
        <PackageProjectUrl>https://berdsk.com.br</PackageProjectUrl>
        <PackageIcon>berdsk-icon.png</PackageIcon>
        <PackageReadmeFile>README.md</PackageReadmeFile>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>
        <RepositoryUrl>https://github.com/berdsk-solutions/sdk-pagarme-v5</RepositoryUrl>
        <RepositoryType>git</RepositoryType>

        <!-- Versioning will be handled by GitVersion in the workflow.
             Fallback version used only when GitVersion / -p:Version is not provided. -->
        <Version Condition="'$(Version)' == ''">1.0.1</Version>

    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="System.Text.Json" Version="10.0.8"/>
        <PackageReference Include="System.Net.Http.Json" Version="10.0.8"/>
    </ItemGroup>

    <ItemGroup>
        <None Include="..\..\Resources\berdsk-icon.png" Pack="true" PackagePath="\"/>
        <None Include="..\..\Resources\logo-pagarme.png" Pack="true" PackagePath="\"/>
        <None Include="..\..\Resources\berdsk-brand.png" Pack="true" PackagePath="\"/>
        <None Include="..\..\README.md" Pack="true" PackagePath="\"/>
    </ItemGroup>

</Project>
